### ISSUE TITLE
Fedora menu doesnt open

### ISSUE THREAD

**Issue by comradesakura** [Fedoraware/Fedoraware#822] opened 2022-11-20 02:50 UTC
Convar panel_test_title_safe has conflicting FCVAR_CHEAT flags (child: FCVAR_CHEAT, parent: no FCVAR_CHEAT, par error in console

**Comment by BLS01** [comment] 2022-11-20 03:42
PC Issue WI-FI Issue House Issue Country Issue Game Issue

**Comment by lnx00** [comment] 2022-11-20 13:05
Try removing your mods/huds and see if they're causing this.

**Comment by xxmyn** [comment] 2022-11-25 03:53
it is 1000000000% because of M-Feds "Close Menu on Unfocus" check not working properly and closing the menu constantly, try editing your config from the text file (if it's named default.fw it will load automatically) and setting the unfocus check to false.

**Comment by johnathon-walnut** [comment] 2022-11-25 07:49
It works properly everything I do is perfect

**Comment by johnathon-walnut** [comment] 2022-11-25 07:50
Have you considered he might have just changed the menu key lol

**Comment by xxmyn** [comment] 2022-11-25 08:27
> Have you considered he might have just changed the menu key lol

insert always works to open the menu, this was an issue I experienced and I had to turn off the option (i checked with breakpoints b4 u ask)

**Comment by johnathon-walnut** [comment] 2022-11-25 09:00
I'm yet to have an issue with the thing I added stop having weird issues

**Comment by xxmyn** [comment] 2023-08-05 12:46
The most I can do is change it to be default off, it's hard to reproduce anyway, goodluck!

**Closed by xxmyn** 2023-08-05 12:46 UTC
Labels: bug
