### ISSUE TITLE
Client.dll error

### ISSUE THREAD

**Issue by Havikclericofchaos** [Fedoraware/Fedoraware#1076] opened 2023-10-02 12:23 UTC
**Fedoraware Version Date:** I downloaded it on 1 october 2023
**Windows Version:**    <Windows 10 Pro>

## Description:
Every time i start the fedora loader mid inject is says client.dll error

## Steps to reproduce:
Idk why it is happening so i cannot give an explanation tho i do know that if i install the game inject fedora ware it works for that time but the next time i start tf2 it gives me the error

1. Inject fedoraware
2. Close tf2
3. inject again

## Additional info:
I get this error with the hack mismis2.dll but it doesn t happen with SeOwned

**Comment by lnx00** [comment] 2023-10-02 12:38
Duplicate of #1059

**Closed** 2023-10-02 12:39 UTC
