### ISSUE TITLE
Request: Shoot lowest choked packet

### ISSUE THREAD

**Issue by FFJ11** [Fedoraware/Fedoraware#698] opened 2022-09-13 11:41 UTC
![image](https://user-images.githubusercontent.com/102504389/189891898-16c1f3cb-4f9b-4bcb-b08e-8cf2f7ffa5f4.png)

Shooting the lowest choked packet might increase the chance of hitting a fakelag

**Comment by lnx00** [comment] 2022-09-13 17:11
Duplicate of #663

**Closed by lnx00** 2022-09-13 17:11 UTC
