### ISSUE TITLE
ESP setting "Ignore team: Only friends" does not work 

### ISSUE THREAD

**Issue by prescionx** [Fedoraware/Fedoraware#1017] opened 2023-08-30 18:06 UTC
**Fedoraware Version Date:**   [29-AGU-2023](https://github.com/Fedoraware/Fedoraware/commit/e2d283cac2c321264db67f55d113a1e0a63009d3)
**Windows Version:**  Microsoft Windows 10 Home 10.0.19045 Build19045 

## Configs used:
General: [https://hastebin.com/share/oseredoqat.json](https://hastebin.com/share/oseredoqat.json)
Visual [https://hastebin.com/share/iyogabigov.json](https://hastebin.com/share/iyogabigov.json)

## Description:
Even though we are friends with the player on Steam, he cannot be defined as a friend in the fedoraware playerlist
Assigning it manually to Friend doesn't fix the ESP Draw problem either. When I select "Ignore team: only friends" from ESP, the esp does not draw the player. When i select Ignore team Off, then the friended player drawning in Different color

## Steps to reproduce:
I dont know the solution, you guys did a great job with FW, im sure you guys can handle this too.

## Additional info:
devloper plz fix im poor i cant see my frind thru' wallz plz

**Comment by lnx00** [comment] 2023-08-30 19:44
Probably caused by this: 3e86106c8fee8fc3427318868ef953d2a3111838
I'll have a look at it later.

**Comment by GC634** [comment] 2023-08-30 23:22
if (g_EntityCache.IsFriend(nIndex)) {
    const size_t FONT = FONT_ESP_COND;
    const int offset = g_Draw.m_vecFonts[FONT].nTall / 4;
    
    std::vector<std::wstring> cond_strings = GetPlayerConds(Player);
    
    const wchar_t* friendText = L"FRIEND";
    g_Draw.String(FONT_ESP_COND, nTextX, y + nTextOffset, Colors::Cond, ALIGN_DEFAULT, friendText);
    
    nTextOffset += g_Draw.m_vecFonts[FONT].nTall;
}

Could be better. I think so at least.

**Comment by xxmyn** [comment] 2023-08-31 01:06
I believe this is fixed as of PR #1019

**Comment by xxmyn** [comment] 2023-08-31 12:32
I retract my previous statement

**Comment by GC634** [comment] 2023-08-31 13:36
Yeah. It's worse now. I think that it's my fault.

**Comment by prescionx** [comment] 2023-09-01 18:13
may its caused by searching and marking friends func?
bump.

**Comment by prescionx** [comment] 2023-09-10 10:54
bump. any progress?

**Comment by xxmyn** [comment] 2023-09-10 10:55
hint: none of the friend visual stuff works rn, be patient.

**Closed** 2023-09-10 11:49 UTC
Labels: bug
