### ISSUE TITLE
The Crit indicator

### ISSUE THREAD

**Issue by RobertKnowsWhat** [Fedoraware/Fedoraware#657] opened 2022-08-17 13:49 UTC
Fedoraware that was updated a few hours ago I think

Basically I can't see the bucket increase, and sometimes it does but it just stays in the very same number ex. before>300, after>300

I just cant see it.

**Comment by HutchyBean** [comment] 2022-08-17 14:05
This was not known!!!

**Comment by RobertKnowsWhat** [comment] 2022-08-17 17:49
funny sarcasm but I just want it fixed

**Comment by HutchyBean** [comment] 2022-08-17 19:20
Developers are not smart enough !!!!!

**Comment by Cossegosse** [comment] 2022-08-30 08:55
human issue

**Comment by xxmyn** [comment] 2022-09-14 11:43
duplicate of #545

**Closed by xxmyn** 2022-09-14 11:43 UTC
Labels: bug
