### ISSUE TITLE
Projectile Aimbot does not Target Pyros?(With Video :O)

### ISSUE THREAD

**Issue by Muffinmaker2** [Fedoraware/Fedoraware#1003] opened 2023-08-19 10:27 UTC
**Fedoraware Version Date:**  Aug 16, 2023 
**Windows Version:** Windows 11 22H2 Build 22521.1848

## Configs used:
https://pastebin.com/k6qntmCm

## Description:
The Projectile Aimbot does not target Pyros. I dont know if there is a "ignore Pyros" flag but i have disabled everything that could be ignored in this tab
![image](https://github.com/Fedoraware/Fedoraware/assets/107619523/e96b0a7d-877c-4130-b710-0c8ea3587a0b) ![image](https://github.com/Fedoraware/Fedoraware/assets/107619523/3bc08cca-956c-4d05-b8a9-b47ddcb42906)
Lé video: https://streamable.com/8lt6rh

1. Enable Projectile Aimbot
2. Shoot at Pyros
3. Nothing happends >:(

**Comment by xxmyn** [comment] 2023-08-19 10:37
Can't reproduce on moving/non-moving pyros with the config provided. Please provide the file created by running the host_writeconfig command in your tf2 console.

**Comment by Muffinmaker2** [comment] 2023-08-19 10:39
https://pastebin.com/Ff6C4YyC

> Can't reproduce on moving/non-moving pyros with the config provided. Please provide the file created by running the host_writeconfig command in your tf2 console.

**Comment by xxmyn** [comment] 2023-08-19 10:44
I still can't recreate the issue, maybe it's the thicc pyro model or windows 11, either way I can't provide support if I can't recreate it but I will leave it open if anyone else is able to.

**Comment by Muffinmaker2** [comment] 2023-08-19 10:45
i will test it with out any custom models gimme a min

**Comment by Muffinmaker2** [comment] 2023-08-19 10:53
yep it was the custom model, removing the model fixes it. I think this can be closed

**Comment by xxmyn** [comment] 2023-08-19 10:54
i have no idea why a custom model would cause that, can you send me the thicc pyro game banana page for research purposes?

**Comment by Muffinmaker2** [comment] 2023-08-19 10:55
Here it is: https://gamebanana.com/mods/193787. I have also a custom model for sniper and the Projectile Aimbot works on that fine

**Comment by xxmyn** [comment] 2023-08-19 11:08
![image](https://github.com/Fedoraware/Fedoraware/assets/70382582/c4828a59-f7ea-4258-89e4-039a0c72a1e2)
drawing a line between local pos and the world space centre of the pyro i can see it is weirdly far down, must be an issue with custom models.

**Comment by Muffinmaker2** [comment] 2023-08-19 11:09
yea 🤷 means no big booby pyro for me 😢 thanks for the help :)

**Comment by xxmyn** [comment] 2023-08-19 11:10
dw, i think the issue has to do with how world space centre is gotten, it can probably be fixed in a few lines :D

**Comment by xxmyn** [comment] 2023-08-19 11:16
Ty for being so helpful in figuring out the problem 👍

**Comment by Muffinmaker2** [comment] 2023-08-19 11:16
always on the hunt for new bugs :)

**Closed** 2023-08-19 11:15 UTC
Labels: bug
