### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by NaleC3D** [Fedoraware/Fedoraware#871] opened 2022-12-23 01:58 UTC
**Fedoraware Version Date:*Last *  

## Description:  
<Always i inject the cheat in tf2 he crash, with no motive>

## Additional context 
One day i inject the cheat with Xenon and he crash tf2, i reset my pc, recompile, re dowload, every and he continue crash

**Comment by xxmyn** [comment] 2022-12-23 08:18
stop using google translate to make github issues.

**Comment by lnx00** [comment] 2022-12-23 13:10
Can't reproduce without config.

**Comment by NaleC3D** [comment] 2022-12-23 14:54
Config Default

**Comment by xxmyn** [comment] 2023-01-01 07:22
my game does not crash when i inject, closing (yes my game is a he)

**Closed by xxmyn** 2023-01-01 07:22 UTC
Labels: bug
